### ISSUE TITLE
ImageMessage test case

### ISSUE THREAD

**Issue by wldfwefwefqe** [lambdaprime/jros2messages#1]
Dear author:

I was trying to use the package to transfer ImageMessage. However, it does not work.

I checked the test case, and it does not include ImageMessage.

https://github.com/lambdaprime/jros2messages/blob/main/jros2messages.tests/src/test/java/id/jros2messages/tests/MessageTests.java

Is it possible to add ImageMessage test case into it? So users of this package could know if it is also working on ImageMessage and how to use it.

Thank you very much in advance.

**Comment by wldfwefwefqe** [comment]
Here is the Java code:

    public static void main(String[] args) throws Exception {
        var client = new JRos2ClientFactory().createClient();
        var topicName = "/image_topic";
        // register a new Subscriber

        client.subscribe(new TopicSubscriber<>(ImageMessage.class, topicName) {
            @Override
            public void onNext(ImageMessage item) {
                System.out.println(item.header.frame_id);
                //System.out.println(item.toString());
                // request next message
                getSubscription().get().request(1);
            }
        });
    }

Here is the error/warning message I received:
ARNING: dataFrag with number 1 already present, ignoring it...
Oct 24, 2023 11:27:50 AM pinorobotics.rtpstalk.impl.behavior.reader.DataFragmentJoiner#458209687-00000104
WARNING: dataFrag with number 2 already present, ignoring it...
Oct 24, 2023 11:27:50 AM pinorobotics.rtpstalk.impl.behavior.reader.DataFragmentJoiner#458209687-00000104
WARNING: dataFrag with number 53 already present, ignoring it...
Oct 24, 2023 11:27:50 AM pinorobotics.rtpstalk.impl.behavior.reader.DataFragmentJoiner#458209687-00000104
WARNING: dataFrag with number 86 already present, ignoring it...
Oct 24, 2023 11:27:50 AM pinorobotics.rtpstalk.impl.behavior.reader.DataFragmentJoiner#458209687-00000104
WARNING: dataFrag with number 87 already present, ignoring it...
Oct 24, 2023 11:27:50 AM pinorobotics.rtpstalk.impl.behavior.reader.DataFragmentJoiner#458209687-00000104
WARNING: dataFrag with number 52 already present, ignoring it...
Oct 24, 2023 11:27:50 AM pinorobotics.rtpstalk.impl.behavior.reader.DataFragmentJoiner#458209687-00000104
WARNING: dataFrag with number 53 already present, ignoring it...

**Comment by lambdaprime** [comment]
Hi @wldfwefwefqe,

Thanks for trying jrosclient

> I checked the test case, and it does not include ImageMessage.

These are unit tests and they are not supposed to be used by the users

> Is it possible to add ImageMessage test case into it? So users of this package could know if it is also working on ImageMessage and how to use it.

Yes, we included it to **jros2client** examples under [ImagesSubscriberApp](https://github.com/lambdaprime/jros2client/blob/09bf656acc7673d9d2dbaa6aae81977affa0c4fe/jros2client.examples/src/ImagesSubscriberApp.java).
